version: '2.4'
services:
# inspircd
  irc-inspircd:
    image: ghcr.io/g-o-o-s/irc.thegoos.cloud:ircd-spoke-prod
    # build stanza used if unable to pull image from repo
    build:
      context: ./docker/inspircd
      dockerfile: Dockerfile
    container_name: irc-inspircd
    restart: unless-stopped
    read_only: true
    ports:
      # irc clients
      - "6697:6697"
      # other servers
      - "7001:7001"
      # inspircd webui
      - "8067:8067"
    volumes:
      - "./docker/inspircd/conf/private:/inspircd/conf/private:ro"
      - "./docker/inspircd/data:/inspircd/data:rw"
      - "./docker/inspircd/logs:/inspircd/logs:rw"
      - "./docker/shared/certs:/inspircd/certs:ro"
      - "./docker/shared/run/inspircd:/run/inspircd:rw"

# thelounge

# traefik

# traefik-cert-exporter or w/e the name is

# inotify + bash oper

